package com.demo.prueba.client.entity;

import com.demo.prueba.client.audit.AuditEntity;
import lombok.*;
import org.hibernate.annotations.GenericGenerator;

import javax.persistence.*;

/**
 * Account Entity.
 *
 * @author bcarrillo.
 * @version 1.0.0
 */
@Getter
@Setter
@Builder
@AllArgsConstructor
@NoArgsConstructor
@Entity(name = "ACCOUNTS")
public class AccountEntity extends AuditEntity {

    /**
     * Serial generated by default.
     */
    private static final long serialVersionUID = 3124269810032793659L;

    @Id
    @GeneratedValue(generator = "UUID")
    @GenericGenerator(name = "UUID", strategy = "org.hibernate.id.UUIDGenerator")
    @Column(name = "ACCOUNT_ID")
    private String accountID;

    @Column(name = "CLIENT_ID")
    private String clientId;

    @Column(name = "ACCOUNT_NUMBER")
    private String accountNumber;

    @Column(name = "TYPE_ACOUNT")
    private String typeAccount;

    @Column(name = "BALANCE")
    private Double balance;

    @OneToOne
    @JoinColumn(name = "CLIENT_ID", referencedColumnName = "CLIENT_ID", insertable = false, updatable = false)
    private ClientEntity clientEntity;



    /**
     * Get entity id.
     */
    public String getId() {
        return accountID;
    }
}
