package com.demo.prueba.client.entity;

import com.demo.prueba.client.audit.AuditEntity;

import lombok.*;
import org.hibernate.annotations.GenericGenerator;

import javax.persistence.*;

/**
 * Clients Entity.
 *
 * @author bcarrillo.
 * @version 1.0.0
 */
@Getter
@Setter
@Builder
@AllArgsConstructor
@NoArgsConstructor
@Entity(name = "CLIENTS")
public class ClientEntity extends AuditEntity {

    /**
     * Serial generated by default.
     */
    private static final long serialVersionUID = -7552263406606916032L;

    @Id
    @GeneratedValue(generator = "UUID")
    @GenericGenerator(name = "UUID", strategy = "org.hibernate.id.UUIDGenerator")
    @Column(name = "CLIENT_ID")
    private String clientID;

    @Column(name = "PERSON_ID")
    private String personId;

    @Column(name = "PASSWORD")
    private String password;

    @OneToOne
    @JoinColumn(name = "PERSON_ID", referencedColumnName = "PERSON_ID", insertable = false, updatable = false)
    private PersonEntity personEntity;


    /**
     * Get entity id.
     */
    public String getId() {
        return personId;
    }
}
