package com.demo.prueba.client.entity;

import com.demo.prueba.client.audit.AuditEntity;
import lombok.*;
import org.hibernate.annotations.GenericGenerator;

import javax.persistence.*;
import java.util.Date;

/**
 * Account Entity.
 *
 * @author bcarrillo.
 * @version 1.0.0
 */
@Getter
@Setter
@Builder
@AllArgsConstructor
@NoArgsConstructor
@Entity(name = "MOVEMENTS")
public class MovementEntity extends AuditEntity {
    /**
     * Serial generated by default.
     */
    private static final long serialVersionUID = 7494720595538232374L;

    @Id
    @GeneratedValue(generator = "UUID")
    @GenericGenerator(name = "UUID", strategy = "org.hibernate.id.UUIDGenerator")
    @Column(name = "MOVEMENT_ID")
    private String movementId;

    @Column(name = "ACCOUNT_ID")
    private String accountID;

    @Column(name = "DATE_MOVEMENT")
    private Date dateMovement;

    @Column(name = "MOVEMENT_TYPE")
    private String movementType;

    @Column(name = "MOVEMENT_VALUE")
    private Double movementValue;

    @Column(name = "AVAILABLE_BALANCE")
    private Double availableBalance;


    @OneToOne
    @JoinColumn(name = "ACCOUNT_ID", referencedColumnName = "ACCOUNT_ID", insertable = false, updatable = false)
    private AccountEntity accountEntity;



    /**
     * Get entity id.
     */
    public String getId() {
        return accountID;
    }
}
