CREATE DATABASE prueba
    

CREATE TABLE PERSONS (
    PERSON_ID VARCHAR(36) PRIMARY KEY,          
    COMPLETE_NAME VARCHAR(100) NOT NULL,         
    GENDER VARCHAR(36) NOT NULL,                     
    AGE INT NOT NULL,                            
    IDENTIFY_NUMBER VARCHAR(20) NOT NULL,       
    ADDRESS VARCHAR(255),                        
    PHONE VARCHAR(20),                           
    STATUS BOOLEAN NOT NULL,                   
    REGISTER_USER VARCHAR(50),                     
    CREATED_DATE DATE DEFAULT CURRENT_DATE NOT NULL,          
    MODIFICATION_USER VARCHAR(50),                                
    LASTMODIFIED_DATE DATE                           
);

CREATE TABLE CLIENTS (
    CLIENT_ID VARCHAR(36) PRIMARY KEY,
	PERSON_ID VARCHAR(36),
    PASSWORD VARCHAR(100) NOT NULL, 
    STATUS BOOLEAN NOT NULL,                   
    REGISTER_USER VARCHAR(50),                     
    CREATED_DATE DATE DEFAULT CURRENT_DATE NOT NULL,          
    MODIFICATION_USER VARCHAR(50),                                
    LASTMODIFIED_DATE DATE 
);

CREATE TABLE ACCOUNTS (
    ACCOUNT_ID VARCHAR(36) PRIMARY KEY,
	CLIENT_ID VARCHAR(36),
    ACCOUNT_NUMBER VARCHAR(100), 
    TYPE_ACOUNT VARCHAR(36) NOT NULL,                   
    BALANCE DECIMAL(10,2),                     
    STATUS BOOLEAN NOT NULL,                   
    REGISTER_USER VARCHAR(50),                     
    CREATED_DATE DATE DEFAULT CURRENT_DATE NOT NULL,          
    MODIFICATION_USER VARCHAR(50),                                
    LASTMODIFIED_DATE DATE 
);

CREATE TABLE MOVEMENTS (
   	MOVEMENT_ID VARCHAR(36) PRIMARY KEY,
	ACCOUNT_ID VARCHAR(36),
    DATE_MOVEMENT DATE NOT NULL, 
    MOVEMENT_TYPE VARCHAR(36) NOT NULL,                
    MOVEMENT_VALUE DECIMAL(10,2) NOT NULL,   
	AVAILABLE_BALANCE DECIMAL(10,2) NOT NULL,  
    STATUS BOOLEAN NOT NULL,                   
    REGISTER_USER VARCHAR(50),                     
    CREATED_DATE DATE DEFAULT CURRENT_DATE NOT NULL,          
    MODIFICATION_USER VARCHAR(50),                                
    LASTMODIFIED_DATE DATE 
);


ALTER TABLE CLIENTS ADD CONSTRAINT FKCLIENTPERSONS FOREIGN KEY (PERSON_ID) REFERENCES PERSONS (PERSON_ID) ON DELETE RESTRICT ON UPDATE RESTRICT;
ALTER TABLE ACCOUNTS ADD CONSTRAINT FKACCOUNTSCLIENTS FOREIGN KEY (CLIENT_ID) REFERENCES CLIENTS (CLIENT_ID) ON DELETE RESTRICT ON UPDATE RESTRICT;
ALTER TABLE MOVEMENTS ADD CONSTRAINT FKMOVEMENTSACCOUNTS FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNTS (ACCOUNT_ID) ON DELETE RESTRICT ON UPDATE RESTRICT;

